      PROGRAM DMF(INPUT,OUTPUT,TAPE5=INPUT,TAPE6=OUTPUT,TAPE7)
C
C     THIS IS DUMMY MAIN PROGRAM TO SET BLANK COMMON STORAGE POINTERS
C     FOR LONG TERM ARRAYS, SOLIDS ARRAY AND SMALL CLOUDS ARRAYS
C
         COMMON/DIMFN/ NS,NSP1,NVL,NSC
         COMMON A(1)
C
C     CDC ONLY
C     COMMON A (SET DIMENSION NEED)
C
         REWIND 7
         READ (5,15) NMAX,MMAX,NS,NVL,NSC
   15    FORMAT (16I5)
C     NMAX-LONG TERM ARRAY DIMENSION IN Z-DIRECTION
C     MMAX-LONG TERM ARRAY DIMENSION IN X-DIRECTION
C     NS-NUMBER OF SOLID FRACTIONS
C     NVL-NUMBER OF VELOCITY PLANES
C     NSC-MAXIMUM NUMBER OF SMALL CLOUDS ALLOWED
C
C     OTHERS
C
C     SET ARRAY POINTERS
         NSP1 = NS+1
         LDIM = NMAX * MMAX
         N1 = 1
C     X
         N2 = N1+LDIM
C     Z
         N3 = N2+LDIM
C     DEPTH
         N4 = N3+LDIM
C     ICODE
         N5 = N4+LDIM
C     CP
         N6 = N5+LDIM
C     THICKP
         N7 = N6+LDIM
C     TOPP
         N8 = N7+LDIM
C     SUM
         N9 = N8+LDIM
C     C
         N10 = N9+LDIM
C     THICK
         N11 = N10+LDIM
C     TOP
         N12 = N11+LDIM
C     ACCUM
         N13 = N12+LDIM
C     U
         N14 = N13+LDIM*NVL
C     W
         N15 = N14+LDIM*NVL
C     SS
         N16 = N15+600*NS
C     TSIDE
         N17 = N16+NSC
C     TTHK
         N18 = N17+NSC
C     TTOP
         N19 = N18+NSC
C     TMASS
         N20 = N19+NSC
C     TX
         N21 = N20+NSC
C     TZ
         NEED = N21+NSC
C
C     FIND PRESENT FIELD LENGTH, ADD LENGTH OF ARRAYS (NEED) AND REQUEST
C     NEW FIELD LENGTH
C
C     CDC ONLY
C     LENF = MEMGET(65B) + 1
C     NEWLEN = LENF+NEED
C     WRITE(6,25) NMAX,MMAX,NS,NVL,NSC,NEED
C  25 FORMAT(/////10X,39HSTORAGE ALLOCATION PARAMETERS FOLLOW.../10X,
C    1 4HNMAX,1X,4HMMAX,3X,2HNS,2X,3HNVL,2X,3HNSC,4X,4HNEED/10X,I3,2X
C    2 ,I3,4X,I2,1X,I3,2X,I3,2X,I6)
C     CALL XRFL(NEWLEN)
C     CDC ONLY
C
         CALL MAIN(A(N1),A(N2),A(N3),A(N4),A(N5),A(N6),A(N7),A(N8),A(N9),
     1    A(N10),A(N11),A(N12),A(N13),A(N14),A(N15),A(N16),A(N17),
     2    A(N18),A(N19),A(N20),A(N21),NMAX,MMAX)
         CALL EXIT
      END



